#!/bin/sh
set -e

. "$(dirname "$0")/fn.sh"

dir="$(dirname "$0")"
cd "$(dirname "$0")"/../

if [ ! -d "$dir/pre-commit-hooks" ]; then
	exit 0
fi

for file in $dir/pre-commit-hooks/*
do
  basename=$(basename "$file")

  set +e
	debug "checking $basename"
  changed $basename
	exitCode="$?"
  set -e

  # "1" represents no files found
  # meaning no files have been changed, so it is safe to continue
	if [ $exitCode = 1 ]; then
		continue
	fi

  sh -e "$file" "$@"
done
