#!/bin/sh
set -e

. "$(dirname "$0")/fn.sh"

githooksdir="$(dirname "$0")"
cd "$(dirname "$0")"/../

if [ ! -d "$githooksdir/pre-commit-hooks" ]; then
	exit 0
fi

ran=false

for file in $githooksdir/pre-commit-hooks/*
do
  project=$(basename "$file")

  set +e
	debug "checking $project"
  changed $project
	exitCode="$?"
  set -e

  # "1" represents no files found
  # meaning no files have been changed, so it is safe to continue
	if [ $exitCode = 1 ]; then
		continue
	fi
  ran = true

  sh -e "$file" "$@"
done


if [ "$ran" = false ]; then
  debug "No pre-commit hooks executed"
fi
